######################################################################
# Automatically generated by qmake (2.01a) dim. févr. 25 10:50:34 2007
######################################################################

QT+=xml
TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/playlist.h src/track.h
SOURCES += src/main.cpp src/playlist.cpp src/track.cpp
